version: '2'
services:
  elasticsearch:
    build:
      context: "es/."
    container_name: elasticsearch
    environment:
      - "http.host=0.0.0.0"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ports:
      - 9200:9200
  kibana:
    build:
      context: "kibana/."
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5601:5601
