version: '2'
services:
  elasticsearch5:
    build:
      context: es5
    container_name: elasticsearch5
    hostname: elasticsearch
    environment:
      - "http.host=0.0.0.0"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - 9200:9200
  kibana5:
    image: docker.elastic.co/kibana/kibana:5.6.1
    container_name: kibana
    links:
      - elasticsearch5
    ports:
      - 5601:5601
